exports.personForm = function(d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Form demo</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Student Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset> <!-- Agrupar campos -->
                        <legend>Name</legend>
                        <label>First Name</label>
                        <input class="w3-input w3-round" type="text" name="fname">
                        <label>Last Name</label>
                        <input class="w3-input w3-round" type="text" name="lname">
                    </fieldset>

                    <fieldset> <!-- Verificação é feita pelo atributo name / os campos pertencem à mesma variável -->
                        <legend>Gender</legend>
                        <input class="w3-radio" type="radio" name="gender" value="male" checked> <!-- Selecionado por omissão -->
                        <label>Male</label>
                        <input class="w3-radio" type="radio" name="gender" value="female">
                        <label>Female</label>
                        <input class="w3-radio" type="radio" name="gender" value="other">
                        <label>Other</label>
                    </fieldset>  
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button> <!-- Botão de envio do http com info do formulário para o servidor -->
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2023 in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            
            </div>
            `
    return pagHTML
}


exports.personPostConfirmPage = function( person, d ){
    return `
    <html>
    <head>
        <title>Aluno: ${person.lname}, ${person.fname}</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>${person.lname}, ${person.fname}</h1>
            </header>

            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
                    <li><b>Name: </b> ${person.lname}, ${person.fname}</li>
                    <li><b>Gender: </b> ${person.gender}</li>
                </ul>
            </div>

            <footer class="w3-container w3-teal">
                <address>Generated by RPCW2023 in ${d} - [<a href="/">Return</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
}